[Colors:View]
BackgroundNormal=#121212
ForegroundNormal=#FFFFFF

[Colors:Window]
BackgroundNormal=#1A2238

[Colors:Selection]
BackgroundNormal=#00D2FF
ForegroundNormal=#000000

[KDE]
widgetStyle=Breeze

[General]
Name=NexusOS-Dark

[Theme]
Name=NexusOS-Dark

[KWin]
Compositing=true

[Compositing]
OpenGLIsUnsafe=false
LatencyPolicy=87
VSyncMethod=1

[PlasmaTheme]
Name=NexusOS-Dark
