context.objects = [
    {
        factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "aion-gaming"
            node.description = "Aion Gaming"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
        }
    }
    {
        factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "aion-chat"
            node.description = "Aion Voice Chat"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
        }
    }
    {
        factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "aion-media"
            node.description = "Aion Media"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
        }
    }
]
