context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            node.name        = "aion-gaming-loopback"
            node.description = "Gaming -> Speakers"
            capture.props = {
                node.name = "aion-gaming"
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.passive = true
                audio.position = [ FL FR ]
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.name        = "aion-chat-loopback"
            node.description = "Chat -> Speakers"
            capture.props = {
                node.name = "aion-chat"
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.passive = true
                audio.position = [ FL FR ]
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.name        = "aion-media-loopback"
            node.description = "Media -> Speakers"
            capture.props = {
                node.name = "aion-media"
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.passive = true
                audio.position = [ FL FR ]
            }
        }
    }
]
